# Generated by Django 5.2.5 on 2025-08-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('role_super_user', 'Super User'), ('role_institute', 'Institute'), ('role_student', 'Student')], default='Student', max_length=20),
        ),
    ]
